apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  DB_USER: bXlzcWx1c2Vy        # base64 for "mysqluser"
  DB_PASSWORD: cGFzc3dvcmQ=    # base64 for "password"
